version: '3'

services:
  alt-sch-go:
    build: . #search for Dockerfile
    container_name: alt_sch_exam
    volumes:
      - .:/go/src/go-docker
    ports:
      - "8080:8080"
    networks:
      - alt_sch

  mysql:
    image: mysql:latest
    #    command:
    #      - '--character-set-server=utf8mb4'
    restart: unless-stopped
    tty: true
    container_name: altSchExam
    ports:
      - "3307:3306"
    volumes:
      - .:/var/lib
      - ./mysql:/var/lib/mysql
      - ./mysql-files:/var/lib/mysql-files
    environment:
      MYSQL_DATABASE: altSchDB
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - alt_sch

networks:
  alt_sch:
    external: true